title: "Wingene"
author: "José Eugênio de Assis Gonçalves"
show_downloads: false
google_analytics: G-VV8V7GTRPD
description: "José Eugênio" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
#remote_theme: pages-themes/modernist@v0.2.0
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
#theme: "minima"

# rss: rss

# kramdown:
#   syntax_highlighter_opts:
#     disable: true

# titles_from_headings:
#   strip_title: true
#   collections: true

# Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "eugeniog@gmail.com"
#twitter_username: "eugeniog"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: eugeniogz
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

# defaults:
#   - scope:
#       path: ""
#       type: posts
#     values:
#       tags: 
#        - other
